# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_auto_20161119_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
