# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_auto_20161205_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='taxon',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 5, 11, 31, 49, 850934, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxon',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 5, 11, 33, 21, 450677, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
