# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_auto_20161212_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_dwca',
            name='uploaded_at',
        ),
    ]
