# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import taxonomy.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_auto_20161212_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwcaTaxon',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('scientificName', models.CharField(max_length=50)),
                ('taxonRank', models.CharField(max_length=50)),
                ('kingdom', models.CharField(max_length=50)),
                ('bibliographicCitation', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='upload_dwca',
            name='dwca',
            field=models.FileField(upload_to='dwca/', validators=[taxonomy.models.validate_file_extension]),
        ),
    ]
