# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0010_auto_20161213_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwcaDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=50)),
                ('occurrenceRemarks', models.CharField(max_length=50)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.DwcaTaxon')),
            ],
        ),
        migrations.CreateModel(
            name='DwcaResourceRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationshipOfResource', models.CharField(max_length=50)),
                ('relatedResourceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rrlink', to='taxonomy.DwcaTaxon')),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.DwcaTaxon')),
            ],
        ),
        migrations.CreateModel(
            name='DwcaVernacular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vernacularName', models.CharField(max_length=50)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.DwcaTaxon')),
            ],
        ),
    ]
