# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
        ('taxonomy', '0014_rawname'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameFinderResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_path_ranks', models.CharField(max_length=255)),
                ('classification_path', models.CharField(max_length=255)),
                ('current_name_string', models.CharField(max_length=255)),
                ('imported_at', models.CharField(max_length=255)),
                ('canonical_form', models.CharField(max_length=255)),
                ('data_source_id', models.IntegerField()),
                ('match_value', models.CharField(max_length=255)),
                ('data_source_title', models.CharField(max_length=255)),
                ('gni_uuid', models.CharField(max_length=255)),
                ('edit_distance', models.IntegerField()),
                ('match_type', models.CharField(max_length=255)),
                ('name_string', models.CharField(max_length=255)),
                ('current_taxon_id', models.CharField(max_length=255)),
                ('taxon_id', models.CharField(max_length=255)),
                ('prescore', models.CharField(max_length=255)),
                ('classification_path_ids', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
            ],
        ),
    ]
