# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0017_namefinderresult_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namefinderresult',
            name='canonical_form',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='classification_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='classification_path_ranks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='current_name_string',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='current_taxon_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='data_source_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='data_source_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='edit_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='gni_uuid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='imported_at',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='match_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='match_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='name_string',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='prescore',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='supplied_name_string',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namefinderresult',
            name='taxon_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
