# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0018_auto_20170102_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namefinderresult',
            name='match_type',
            field=models.IntegerField(null=True),
        ),
    ]
