# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0019_auto_20170102_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namefinderresult',
            name='classification_path_ids',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
