# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
        ('taxonomy', '0020_auto_20170102_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameFinderJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_finder_json', models.TextField()),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
            ],
        ),
    ]
