# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
        ('newislandrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newislandrecord',
            name='established',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='newislandrecord',
            name='invasive_species',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='newislandrecord',
            name='quarantine_interception',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='newislandrecord',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Publication'),
        ),
        migrations.AddField(
            model_name='newislandrecord',
            name='year_detected',
            field=models.IntegerField(null=True),
        ),
    ]
