# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newislandrecords', '0003_auto_20161105_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newislandrecord',
            name='created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='newislandrecord',
            name='updated',
            field=models.DateField(null=True),
        ),
    ]
